version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash docker-entrypoint.sh
#    command: sleep 3600
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SECRET_KEY=fRGVjNTaymiywXEMUAlpHch7a6A4bL5FYvWm3vqysbduKnmcJ1zzuDFjqmJp
      - DJANGO_DEBUG=true
    depends_on:
      - db