version: "3"

services:
  web:
    volumes:
      - .:/code
  stunnel:
    image: easypi/stunnel
    ports:
      - 8001:8001
    volumes:
      - ./stunnel.conf:/etc/stunnel/stunnel.conf:ro
      - ./localhost+1-key.pem:/etc/stunnel/stunnel.key:ro
      - ./localhost+1.pem:/etc/stunnel/stunnel.crt:ro

volumes:
  postgres_data: